name: ia_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+4
  intl: ^0.16.0
  provider: ^3.1.0
  connectivity: ^0.4.4
  http: any
  json_annotation: ^2.0.0
  flutter_credit_card: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons: "^0.7.3"
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/dumbbell_icon.png"


flutter:
  uses-material-design: true
  fonts:
    - family: WorkSans Black
      fonts:
        - asset: assets/fonts/WorkSans-Black.ttf
    - family: WorkSans Bold
      fonts:
        - asset: assets/fonts/WorkSans-Bold.ttf
    - family: WorkSans ExtraBold
      fonts:
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
    - family: WorkSans ExtraLight
      fonts:
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
    - family: WorkSans Light
      fonts:
        - asset: assets/fonts/WorkSans-Light.ttf        
    - family: WorkSans Medium
      fonts:
        - asset: assets/fonts/WorkSans-Medium.ttf    
    - family: WorkSans Regular
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf    
    - family: WorkSans SemiBold
      fonts:
        - asset: assets/fonts/WorkSans-SemiBold.ttf                
    - family: WorkSans Thin
      fonts:
        - asset: assets/fonts/WorkSans-Thin.ttf  
        
  assets:
  - 'assets/animations/'
  - 'assets/images/'
  - 'assets/icons/'

 